export const enum KEYS {
  C = 'C',
  X = 'X',
  Z = 'Z',
  Y = 'Y',
  A = 'A',
  G = 'G',
  L = 'L',
  F = 'F',
  D = 'D',
  B = 'B',
  P = 'P',
  MINUS = '-',
  EQUAL = '=',
  DIGIT_0 = '0',
  DELETE = 'DELETE',
  UP = 'ARROWUP',
  DOWN = 'ARROWDOWN',
  LEFT = 'ARROWLEFT',
  RIGHT = 'ARROWRIGHT',
  ENTER = 'ENTER',
  SPACE = ' ',
  TAB = 'TAB',
  BACKSPACE = 'BACKSPACE',
  ESC = 'ESCAPE',
  PAGEUP = 'PAGEUP',
  PAGEDOWN = 'PAGEDOWN',
  F5 = 'F5',
}

export const HOTKEY_DOC = [
  {
    type: 'universal',
    children: [
      { label: 'Cut', value: 'Ctrl + X' },
      { label: 'Copy', value: 'Ctrl + C' },
      { label: 'Paste', value: 'Ctrl + V' },
      { label: 'Paste as plain text', value: 'Ctrl + Shift + V' },
      { label: 'Quick copy and paste', value: 'Ctrl + D' },
      { label: 'Select All', value: 'Ctrl + A' },
      { label: 'Undo', value: 'Ctrl + Z' },
      { label: 'Restore', value: 'Ctrl + Y' },
      { label: 'Delete', value: 'Delete / Backspace' },
      { label: 'Multiple selection', value: 'Hold down Ctrl or Shift' },
      { label: 'Turn on search and replace', value: 'Ctrl + F' },
      { label: 'Print', value: 'Ctrl + P' },
      { label: 'Close pop-up window', value: 'ESC' },
    ],
  },
  {
    type: 'slide show',
    children: [
      { label: 'Show slide show from the beginning', value: 'F5' },
      {
        label: 'Show slideshow starting from current moment',
        value: 'Shift + F5',
      },
      { label: 'Switch to previous page', value: '↑ / ← / PgUp' },
      { label: 'Switch to next page', value: '↓ / → / PgDown' },
      { label: 'Switch to next page', value: 'Enter / Space' },
      { label: 'Exit show', value: 'ESC' },
    ],
  },
  {
    type: 'Slide Edit',
    children: [
      { label: 'New Slide', value: 'Enter' },
      { label: 'Move canvas', value: 'Space + mouse drag' },
      { label: 'Zoom canvas', value: 'Ctrl + mouse wheel' },
      { label: 'Enlarge canvas', value: 'Ctrl + =' },
      { label: 'Reduce canvas', value: 'Ctrl + -' },
      { label: 'Adapt canvas to current screen', value: 'Ctrl + 0' },
      { label: 'Previous page (unselected element)', value: '↑ / ←' },
      { label: 'Next page (unselected element)', value: '↓ / →' },
      { label: 'Previous page', value: 'Mouse scroll up / PgUp' },
      { label: 'Next page', value: 'Mouse scroll down / PgDown' },
    ],
  },
  {
    type: 'Element operation',
    children: [
      { label: 'Move', value: '↑ / ← / ↓ / →' },
      { label: 'Lock', value: 'Ctrl + L' },
      { label: 'combination', value: 'Ctrl + G' },
      { label: 'Ungroup', value: 'Ctrl + Shift + G' },
      { label: 'Bring to top', value: 'Alt + F' },
      { label: 'Set to bottom', value: 'Alt + B' },
      { label: 'Lock aspect ratio', value: 'Hold down Ctrl or Shift' },
      {
        label: 'Create horizontal/vertical lines',
        value: 'Hold Ctrl or Shift',
      },
      { label: 'Switch focus element', value: 'Tab' },
      { label: 'Confirm image cropping', value: 'Enter' },
    ],
  },
  {
    type: 'Table editing',
    children: [
      { label: 'Focus on next cell', value: 'Tab' },
      { label: 'Insert a line above', value: 'Ctrl + ↑' },
      { label: 'Insert a line below', value: 'Ctrl + ↓' },
      { label: 'Insert a column on the left', value: 'Ctrl + ←' },
      { label: 'Insert a column on the right', value: 'Ctrl + →' },
    ],
  },
  {
    type: 'Chart data editing',
    children: [{ label: 'Focus on the next line', value: 'Enter' }],
  },
  {
    type: 'TextEdit',
    children: [
      { label: 'Bold', value: 'Ctrl + B' },
      { label: 'italic', value: 'Ctrl + I' },
      { label: 'underline', value: 'Ctrl + U' },
      { label: 'inline code', value: 'Ctrl + E' },
      { label: 'Superscript', value: 'Ctrl + ;' },
      { label: 'subscript', value: `Ctrl + '` },
      { label: 'Selected paragraph', value: `ESC` },
    ],
  },
]
